version: '3.8'
services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      BASE_URL: http://localhost:3000
    volumes:
      # - .:/app
      - ./uploads:/app/uploads
      - ./files:/app/files
    
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
